require("config.lazy")
require("config.common")
require("config.copilot")
require("config.lspconfig")
require("config.nvim-cmp")
require("config.treesitter")
require("config.neo-tree")
require("config.conform")
-- require("config.telescope")
require("keymaps")
